In [1]:
#NUMPY (Numerical Python)
#Array'ler çok boyutlu array'ler ve matrisler üzerinde çalışma imkanı
#Matematiksel ve istatiksel hesaplamalar
#Verimli veri saklama ve vektörel operasyonlardır.

In [2]:
import numpy as np

In [6]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
ab = []

for i in range(0, len(a)):
  ab.append(a[i] * b[i])

ab

[2, 6, 12, 20]

In [7]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a * b

array([ 2,  6, 12, 20])

In [8]:
#Numpy listelere göre neden daha iyi?
#Daha hızlıdır çünkü sabit tipte veri tutar, yani  verimli veri saklar bundan dolayı hızlıdır.
#Yüksek seviyeden işlemler yapma imkanı sağlamasıdır.

In [18]:
#Numpy array'i oluşturmak (Creating Numpy Arrays)

np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [19]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.random.randint(0, 10, size=10)

array([3, 1, 2, 1, 6, 2, 0, 4, 5, 2])

In [21]:
np.random.normal(10, 4, (3,4))

array([[12.60512671, 16.99181636,  8.77004149, 15.14102868],
       [11.12611975, 13.65181359, 12.39191682, 15.96594596],
       [ 7.37698175,  1.94234621,  1.12357372, 13.0709083 ]])

In [ ]:
#Numpy Array Özellikleri (Attibutes of Numpy Arrays)
# ndim: boyut sayısı
# shape: boyut bilgisi
# size: toplam eleman sayısı
# dtype: array veri tipi

In [27]:
a = np.random.randint(10, size=5)
a

array([2, 5, 8, 6, 5])

In [28]:
a.ndim

1

In [29]:
a.shape

(5,)

In [31]:
a.size

5

In [32]:
a.dtype

dtype('int64')

In [ ]:
#Yeniden Şekillendirme (Reshaping)

In [33]:
np.random.randint(1,10,size=9)

array([5, 9, 1, 3, 5, 8, 7, 8, 7])

In [34]:
np.random.randint(1,10,size=9).reshape(3,3)

array([[6, 6, 9],
       [5, 5, 3],
       [6, 1, 5]])

In [35]:
ar = np.random.randint(1,10,size=9)

In [36]:
ar.reshape(3,3)

array([[5, 2, 9],
       [2, 4, 1],
       [4, 2, 3]])

In [37]:
#Index Seçimi (Index Selection)

In [39]:
a = np.random.randint(10, size=10)
a[0]
a[0:3]

array([6, 8, 4])

In [41]:
m = np.random.randint(10, size=(3,5))
m

array([[6, 1, 3, 7, 9],
       [1, 6, 3, 7, 8],
       [9, 2, 9, 6, 6]])

In [42]:
m[0, 0]

6

In [43]:
m[1, :]

array([1, 6, 3, 7, 8])

In [44]:
m[:, 1]

array([1, 6, 2])

In [45]:
m[0:2 , 0:3]

array([[6, 1, 3],
       [1, 6, 3]])

In [ ]:
#Fancy Index

In [48]:
v = np.arange(0,30,3)
v[1]
v[4]

12

In [50]:
catch = [1,2,3]

In [51]:
v[catch]

array([3, 6, 9])

In [ ]:
#Numy'da Koşullu İşlemler

In [52]:
v = np.array([1,2,3,4,5])

In [53]:
#Klasik Döngü İle

ab = []
for i in v:
  if i < 3:
    ab.append(i)


In [55]:
# Numpy ile
v < 3

array([ True,  True, False, False, False])

In [56]:
v[v < 3]

array([1, 2])

In [57]:
#Matematiksel İşlemler
v = np.array([1,2,3,4,5])

In [58]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [59]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [60]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [62]:
a = np.array([[5,1],[1,3]])
b = np.array([[12],[10]])

np.linalg.solve(a,b)


array([[1.85714286],
       [2.71428571]])